# Generated by Django 5.1.5 on 2025-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_auth_app', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='SRE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Devops', max_length=100),
        ),
    ]
